server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://101.200.167.72/bc_promote?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 101.200.167.72
    port: 6379
    password: 11223